name = "airportal-clone"
main = "src/index.js"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "airportal-db"
database_id = ""

[[r2_buckets]]
binding = "R2"
bucket_name = "airportal-files"

[triggers]
crons = ["0 0 * * *"]

[vars]
ADMIN_EMAIL = ""
ADMIN_PASSWORD = ""
COLA_KEY = ""
SMTP_EMAIL = ""
SMTP_CODE = ""
SOCIAL_APPID = ""
SOCIAL_KEY = ""
TURNSTILE_KEY = ""
